engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
ratings:
  paths:
    - "tslearn/"
exclude_paths:
- "tslearn/**.c"
- "tslearn/docs/**"
